# This is a generated file. Not intended for manual editing.
services:
  basket.api:
    build:
      context: "/Users/soaadabdelaziz/EShopMicroservices./src"
      dockerfile: "Services/Basket/Basket.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Basket.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "basketapi:dev"
    ports: []
    volumes:
    - "/Users/soaadabdelaziz/EShopMicroservices./src/Services/Basket/Basket.API:/app:rw"
    - "/Users/soaadabdelaziz/EShopMicroservices./src:/src:rw"
    - "/Users/soaadabdelaziz/.microsoft/usersecrets:/home/app/.microsoft/usersecrets"
    - "/Users/soaadabdelaziz/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
  catalogapi:
    build:
      context: "/Users/soaadabdelaziz/EShopMicroservices./src"
      dockerfile: "Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Catalog.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "/Users/soaadabdelaziz/EShopMicroservices./src/Services/Catalog/Catalog.API:/app:rw"
    - "/Users/soaadabdelaziz/EShopMicroservices./src:/src:rw"
    - "/Users/soaadabdelaziz/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
  discount.grpc:
    build:
      context: "/Users/soaadabdelaziz/EShopMicroservices./src"
      dockerfile: "Services/Discount/Discount.Grpc/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Discount.Grpc.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "discountgrpc:dev"
    ports: []
    volumes:
    - "/Users/soaadabdelaziz/EShopMicroservices./src/Services/Discount/Discount.Grpc:/app:rw"
    - "/Users/soaadabdelaziz/EShopMicroservices./src:/src:rw"
    - "/Users/soaadabdelaziz/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
