

services:
  catalogdb:
    image: postgres
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
  basketdb:
    image: postgres
    volumes:
      - postgres_basket:/var/lib/postgresql/data/
  distributedcache:
    image: redis
    
  orderDb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
      - MSSQL_PID=Express
    ports:
        - "1433:1433"

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:

